services:
  web:
    build: .
    ports:
      - '8000:8000'
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
