[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py"]
addopts = "-q --maxfail=1"

# Optional: test marks you may use later
markers = [
  "api: API tests using DRF client",
  "unit: unit tests without DB"
]